### ISSUE TITLE
[Error: Failed to read bitmap]

### ISSUE THREAD

**Issue by devbks** [jonathanpalma/react-native-tesseract-ocr#10]
i'm getting this error as log with english traineddata
the complete error is 
'OCR Error: ', { [Error: Failed to read bitmap] framesToPop: 1, code: 'An error occurred' }

**Comment by jonathanpalma** [comment]
Heey @devbks  Thank you for your support opening an issue. It looks like the bitmap couldn't be created from the path that you specified. I found you are using [react-native-camera](https://github.com/lwansbrough/react-native-camera) on your [stackoverflow question](http://stackoverflow.com/questions/41362503/react-native-tesseract-ocr-error-failed-to-read-bitmap) so, let me test it and I will try to make it works. Meanwhile I recommend you to use [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker) like in this lib [demo](https://github.com/jonathanpalma/react-native-tesseract-ocr/blob/master/tesseractOcrSample/index.js)

**Comment by Thomeuxe** [comment]
Same error here.
The path returned by the react-native-camera component is : "file:///storage/emulated/0/DCIM/IMG_20170102_135548.jpg"

**Comment by jonathanpalma** [comment]
@Thomeuxe could you give me more information about how are you getting the path of your image? libs? some code?

**Comment by AnotherHermit** [comment]
I solved this issue by simply removing 'file://' from the start of the path returned from the react-native-camera component.

**Comment by jonathanpalma** [comment]
@AnotherHermit Thank you!! I just test it and as you said, it's just necessary to remove 'file://' from the start of the path returned from `react-native-camera` to make it works.

**Comment by fazeelzama20** [comment]
@AnotherHermit Getting same error, How do you remove 'file://' from the start of path? can you please help?

**Comment by fazeelzama20** [comment]
@jonathanpalma I have removed 'file://' from path, then also it is giving same error. Following is the error.
`data path /storage/emulated/0/DCIM/IMG_20171211_164757.jpg
index.js:81 [React Transform HMR] Patching ScanVIN
/src/screens/ScanVIN.map?platform=android&runModule=false&entryModuleOnly=true:85 OCR Error:  Error: Failed to read bitmap
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:347)
    at MessageQueue.js:137
    at MessageQueue.__guard (MessageQueue.js:265)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:72
/src/screens/ScanVIN.map?platform=android&runModule=false&entryModuleOnly=true:87 undefined`

**Comment by jonathanpalma** [comment]
@fazeelzama20 are you using `react-native-camera` or  `react-native-image-picker`? Could you provide more information about how are you getting the image path?

**Comment by fazeelzama20** [comment]
@jonathanpalma I am using react-native-camera and code is shown below
`takePicture = () => {
    var path = "";
    this.camera.capture().done(function(data){
      path = data.path.replace('file://', '');
      console.log('data path', path);
    });
    //start of implementing tesseract OCR
    RNTesseractOcr.startOcr(path, "LANG_ENGLISH")
    .then((result) => {
      this.setState({ ocrResult: result });
      console.log("OCR Result: ", result);
    })
    .catch((err) => {
      console.log("OCR Error: ", err);
    })
    .done((data) => {
      console.log(data);
    });
    //end of implementing tesseract OCR
  }`

**Comment by fazeelzama20** [comment]
@jonathanpalma Any suggestion please?

**Comment by sinaazimii** [comment]
> 
> 
> Same error here.
> The path returned by the react-native-camera component is : "file:///storage/emulated/0/DCIM/IMG_20170102_135548.jpg"

hey , i am having the same issue but my problem is the path that RNCamera gives me is this and when i try to reach the picture on my phone there is no files in that directory !

file:///data/user/0/com.imageprocessing/cache/Camera/34268a90-bacd-4d47-9cb9-e0e03e4ab610.jpg

 how should i change that to DCIM folder ?
