### ISSUE TITLE
Poor text outcome

### ISSUE THREAD

**Issue by johnrosenbaud** [jonathanpalma/react-native-tesseract-ocr#11]
Hello, I am getting extremely poor text outcome, something like 10%, pure gibberish, when running on Android. I must have placed the wrong eng.traineddata file OR in the wrong folder. I am running the tesseractOcrSample, demo, and added the eng.traineddata file here:
`tesseractOcrSample/node_modules/react-native-tesseract-ocr/android/src/main/assets/tessdata/eng.traineddata` 
I took this eng.traineddata file from tesseract.js nodeJS module (located in `tesseract.js-core/examples/canvas/eng.traineddata`) 
do I need to place it in another folder? Or do I need another file altogether? What Tesseract version is running in this Android module? Do I need to 'extract' anything?
Thanks very much in advance, also for your work.
John

**Comment by jonathanpalma** [comment]
Heeey @johnrosenbaud try to place the traineddata files for each lang you want to use inside `[YOUR_PROJECT]/android/src/main/assets/tessdata` and try to get the traineddata files from the official tesseract's repo

**Comment by johnrosenbaud** [comment]
Hey @jonathanpalma  thanks for your response, I've added the Tesseract 3.04 version (is it the right version?) files to the tesseractOcrSample sample project included as example -- as you suggested, in  `tesseractOcrSample/android/src/main/assets/tessdata,

both (tried both and separately, respectively) the `eng.traineddata` file and:

`eng.cube.bigrams
eng.cube.fold
eng.cube.lm
eng.cube.nn
eng.cube.params
eng.cube.size
eng.cube.word-freq
eng.tesseract_cube.nn
eng.traineddata`

It outputs 10% circa of a english, standard font high quality screenshot, rest is random letters/words, gibberish. 

It may be that the 3.04 eng.traineddata it's the wrong version and 3.02 or something else is the correct one? Or maybe I am placing them in the wrong directory?

Thanks again,

John

**Comment by jonathanpalma** [comment]
@johnrosenbaud you're welcome!! It seems a bit strange but let me review the documentation and do some testing today because I have identified that the library that was implemented for android has been updated and it mentions something about version incompatibility for traineddata files :thinking: Thank you for your support to make this project grow!!

PD: It would be great if you can provide the image with which you are doing your tests to include it at the time of doing mine and be able to help you

**Comment by johnrosenbaud** [comment]
Thanks @jonathanpalma here's the picture and the text output:

![valentino-text-message](https://cloud.githubusercontent.com/assets/25109658/22308257/3901ad7e-e314-11e6-965f-441ea3929fc4.jpg)

OCR Result: < Menage: Luis Deml

Left 1 message m >>. nanny
Deahnn wmh 3 Procurement wssu?
and 3.4mm mm mm audnur

etc. etc.

This a screenshot of the folder structure:

<img width="1272" alt="tessdata_screenshot" src="https://cloud.githubusercontent.com/assets/25109658/22308383/b007dd26-e314-11e6-9052-26d6a7cf1dbe.png">

**Comment by johnrosenbaud** [comment]
<img width="419" alt="android_emulator_tesseract" src="https://cloud.githubusercontent.com/assets/25109658/22308802/78604eec-e316-11e6-8696-f837bb5beb08.png">

**Comment by johnrosenbaud** [comment]
Solved. It wasn't due to placing the eng.traineddata file correctly, they are by default. The poor text outcome was due to the pre-defined ImagePicker options set to 500 px for height and weight which prevents a good text output quality, and must be set to 2000 or higher to get the right output. Thanks for your assistance.

**Comment by jonathanpalma** [comment]
@johnrosenbaud You're welcome!

**Comment by AmaruNozomi** [comment]
Hello, I have the same issue right now.
In which location I can change the Image Picker options for height and weight?
Thank you in advance

**Comment by chetankotkar** [comment]
Hello, I have image of width:4160 and height:3120  I get the very poor result like below..
[WTWW .2; i“: 1.,
    m a s g
    WW 1;; 0-; .. {
    t; 0 ‘4‘ ‘ *1'
    Q: a ‘ ,9 3?,
    F o "' '
    -- s:
    > O.
    8 v .
    9 9 3 N 8
    . O . N '5 M Q 3: O '
    ‘ '- -; ‘ (D O _
    _ Mi](url)

can you please help. i cant find the cause of poor output.

**Comment by michtnt** [comment]
@chetankotkar did you figure out how to fix it?

**Comment by samprogrammer1** [comment]
> Hello, I have image of width:4160 and height:3120 I get the very poor result like below.. [WTWW .2; i“: 1., m a s g WW 1;; 0-; .. { t; 0 ‘4‘ ‘ *1' Q: a ‘ ,9 3?, F o "' ' -- s: > O. 8 v . 9 9 3 N 8 . O . N '5 M Q 3: O ' ‘ '- -; ‘ (D O _ _ Mi](url)
> 
> can you please help. i cant find the cause of poor output.

i also face this issue how to solve bro
