### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by fair-man** [jonathanpalma/react-native-tesseract-ocr#120]
I am trying to run an example https://github.com/jonathanpalma/react-native-tesseract-ocr/blob/master/example/App.js but cant do it

steps to reproduce:

1. Create a new project with npm `npx react-native init testproject`
2. Install react-native-tesseract-ocr library and link dependencies `npm i react-native-tesseract-ocr --save` `react-native link react-native-tesseract-ocr`
3. Copy from https://github.com/jonathanpalma/react-native-tesseract-ocr/blob/master/example/App.js and paste to testproject/App.js
3. Install dependencies and run project `npm i && npm run android`
4. Run example in android emulator.

**Actual result: [Error: java.io.IOException: Could not create directory]**

<img width="282" alt="Screenshot_2" src="https://user-images.githubusercontent.com/11162127/131241733-86fcb4b9-b77d-4179-82d3-249bc8f49cb8.png">

**Comment by fair-man** [comment]
https://github.com/jonathanpalma/react-native-tesseract-ocr/issues/86
https://github.com/jonathanpalma/react-native-tesseract-ocr/issues/89

Doesn't help solve the problem.

**Comment by manishbss-sdei** [comment]
@fair-man  did you add the eng.traineddata file in your project?

**Comment by fair-man** [comment]
> @fair-man did you add the eng.traineddata file in your project?

No, I didn't. Where can I get the eng.traineddata file and where should I put it in my project?

**Comment by najeeb2113** [comment]
kept the trained data in specified directory still files doesnt work
coud not create directory

**Comment by saurabh-nandan** [comment]
I am also getting the same error. Could you please provide eng.traineddata file, it's not there in the project.

**Comment by Ajayg96** [comment]
react-native-tesseract-ocr uses [tess-two](https://github.com/rmtheis/tess-two) library for Android which is no longer maintained. If you still want to use it you can find trained data files [here](https://github.com/tesseract-ocr/tessdata/tree/3.04.00)
