### ISSUE TITLE
Custom languages version 2.0.3 not Work

### ISSUE THREAD

**Issue by kittipongkp** [jonathanpalma/react-native-tesseract-ocr#123]
**Describe the bug**

**Dependencies (please complete the following information):**
 - react: [e.g. 16.11.0]
 - react-native: [e.g. 0.62.2]
 - react-native-tesseract-ocr: [e.g. 2.0.3]

Custom language

Add custom.languages to
android/app/src/main/assets/tessdata/custom.traineddata

and use  LANG_CUSTOM not Work

custom.traineddata from https://github.com/tesseract-ocr/tessdata

**Comment by Thanhal-P-A** [comment]
+1
