### ISSUE TITLE
Example outdated

### ISSUE THREAD

**Issue by theneekz** [jonathanpalma/react-native-tesseract-ocr#124]
**Describe the bug**
Hey there! I am forking this repo in an effort to add iOS compatibility. I already have linked the native tesseract ios module to react native in a personal project, but there are a few extra steps to getting it added to a package it seems. I'm trying to test by running the example from this repo and it's had a ton of issues. I finally got it to a good spot but am still having trouble getting it working. Is there any chance the original contributors could get the example up and running? Maybe add a README file? 

**To Reproduce**
1. Fork repo
2. Clone
3. `cd example`
4. `yarn`
5. `cd ios;pod install;cd ..`
6. `yarn start`
7. `yarn ios` or `yarn android`

**Expected behavior**
An ios simulator or android emulator opens the example app.

**Comment by jonathanpalma** [comment]
I can give it a try, can you please share the fork?

**Comment by theneekz** [comment]
The fork I am struggling with is - https://github.com/theneekz/react-native-tesseract-ocr
