### ISSUE TITLE
java.io.IOException: Could not create directory 

### ISSUE THREAD

**Issue by zineKaushal** [jonathanpalma/react-native-tesseract-ocr#134]
'react-native-tesseract-ocr' this library working fine in emulator but not working in  phone (apk)

**Comment by HipppB** [comment]
This is due to a change in android API, you must be using a different android version on your simulator and on your phone
You can check the fix I found just here https://github.com/jonathanpalma/react-native-tesseract-ocr/pull/127
It's only one line to change in the code.

Hope it helps
