### ISSUE TITLE
package doesnt build

### ISSUE THREAD

**Issue by Neel-shetty** [jonathanpalma/react-native-tesseract-ocr#142]
**Describe the bug**
can't build the app after installing the package

**Dependencies (please complete the following information):**
 - react: 18.1.0
 - react-native: 0.70.6
 - react-native-tesseract-ocr: 2.0.3

**To Reproduce**
1. initialize a new react native project
2. yarn add react-native-tesseract-ocr 
3. yarn react-native run-android

**Error message**
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\react\temp\node_modules\react-native-tesseract-ocr\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-tesseract-ocr'.
> Plugin with id 'maven' not found.

* Try:
* Get more help at https://help.gradle.org

BUILD FAILED in 15s

    at makeError (D:\react\temp\node_modules\execa\index.js:174:9)
    at D:\react\temp\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\react\temp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\react\temp\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Expected behavior**
should run the app on the emulator

**Smartphone (please complete the following information):**
 - Device: pixel 4
 - OS: android

**Comment by killatsignlife** [comment]
Hello, 
What do you did to solve this problem? 
```
1: Task failed with an exception.        
-----------                              
* Where:                                 
Build file 'C:\leite\ic_120323\react-native-tesseract-ocr\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-tesseract-ocr'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-tesseract-ocr'.
> compileSdkVersion is not specified.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

I `clone`  **react-native-tesseract-ocr** to try run the **example project**, but I stuck in this problem. I tried to start a project from zero using this [tutorial](https://ameya-upalanchi18.medium.com/how-to-use-tesseract-ocr-in-react-native-android-without-expo-55827f5a2eb5), but same problem.

Another thing, I alter `gradle-wrapper.properties`  `distributionUrl` value to `https\://services.gradle.org/distributions/gradle-7.4-bin.zip`.

**Comment by karam-mustafa** [comment]
> Hello, What do you did to solve this problem?
> 
> ```
> 1: Task failed with an exception.        
> -----------                              
> * Where:                                 
> Build file 'C:\leite\ic_120323\react-native-tesseract-ocr\android\build.gradle' line: 23
> 
> * What went wrong:
> A problem occurred evaluating project ':react-native-tesseract-ocr'.
> > Plugin with id 'maven' not found.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> A problem occurred configuring project ':react-native-tesseract-ocr'.
> > compileSdkVersion is not specified.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> ```
> 
> I `clone` **react-native-tesseract-ocr** to try run the **example project**, but I stuck in this problem. I tried to start a project from zero using this [tutorial](https://ameya-upalanchi18.medium.com/how-to-use-tesseract-ocr-in-react-native-android-without-expo-55827f5a2eb5), but same problem.
> 
> Another thing, I alter `gradle-wrapper.properties` `distributionUrl` value to `https\://services.gradle.org/distributions/gradle-7.4-bin.zip`.

Did you solve it? I had the same problem!

**Comment by umutmisket** [comment]
I think there is no valid solution. I had the same issue.
