### ISSUE TITLE
getting "java.io.IOException: Could not create directory" error

### ISSUE THREAD

**Issue by wadekar9** [jonathanpalma/react-native-tesseract-ocr#151]
getting "java.io.IOException: Could not create directory" error after emitting TesseractOcr.recognize() event. please check out the mentioned below code for more info.

**Dependencies (please complete the following information):**
 - react: 17.0.1
 - react-native: 0.64.0
 - react-native-tesseract-ocr: ^2.0.3

##Code : 

import TesseractOcr, { LANG_ENGLISH, LEVEL_WORD } from 'react-native-tesseract-ocr';

const tesseractOptions = { level : LEVEL_WORD };
  try {

    const recognizedText = await TesseractOcr.recognize(
      "file:///data/user/0/com.mill/cache/react-native-image-crop-picker/images.jpeg",
      LANG_ENGLISH,
      tesseractOptions,
    );
    console.log(recognizedText);
  } catch (err) {
    console.error(err.message);
  }

<img width="693" alt="Screenshot 2023-03-04 at 6 45 24 PM" src="https://user-images.githubusercontent.com/107600846/222903908-c95d1ad9-daec-4576-8b64-d8f2e112d483.png">

**Comment by demon3z** [comment]
This problem appeared on my side. I found out that it was a problem with my Android 11 version. I need to obtain the permissions of all files, and I solve it after obtaining it.
