### ISSUE TITLE
[Error: Failed to read bitmap]

### ISSUE THREAD

**Issue by gpminsuk** [jonathanpalma/react-native-tesseract-ocr#17]
Keep getting error
03-22 07:04:04.571  3226  3353 I ReactNativeJS: 'OCR Error: ', { [Error: Failed to read bitmap] framesToPop: 1, code: 'An error occurred' }

It is a simple project. react-native init, and then just installed react-native-tesseract-ocr.
And then I added text.png image in /images/ directory under project root directory and called below code in componentDidMount function.

RNTesseractOcr.startOcr('./images/text.png', 'LANG_ENGLISH')
      .then((result) => {
        console.log("OCR Result: ", result);
      })
      .catch((err) => {
        console.log("OCR Error: ", err);
      })
      .done();

Any suggestions?

**Comment by jonathanpalma** [comment]
You have to provide the absolute path instead the relative. You can check it out at the tesseractSample in this repo.

**Comment by gpminsuk** [comment]
I couldn't find the example. How can I get absolute path from a static image file in the project?

**Comment by jonathanpalma** [comment]
@gpminsuk I recommend you to use a tool like [react-native-image-picker](https://github.com/react-community/react-native-image-picker) to get the absolute path of the images you want to process. In the case that you're trying to use static image files maybe [this](https://willowtreeapps.com/ideas/react-native-tips-and-tricks-2-0-managing-static-assets-with-absolute-paths/) could help you
