### ISSUE TITLE
Cancel the request

### ISSUE THREAD

**Issue by DavitVosk** [jonathanpalma/react-native-tesseract-ocr#20]
Is there an option to cancel the OCR request before it is finished?

**Comment by jonathanpalma** [comment]
Thank you @DavitVosk
I'm working on a new release (for android) that includes support for black and white lists. I will consider to add this essential function to it. BTW I don't know how I hadn't thought about including that before :sweat_smile:

**Comment by DavitVosk** [comment]
I am happy giving you a new idea)). Can you please say me when the new release will be ready? Also if possible can you do this before other changes

**Comment by jonathanpalma** [comment]
You're welcome @DavitVosk 
Let me work on that this week and I hope to publish the new release this weekend. 
[Here](https://github.com/jonathanpalma/react-native-tesseract-ocr/projects/1) are the enhancements that I consider to include for this version.

**Comment by jonathanpalma** [comment]
@DavitVosk this has been released in v2

**Comment by jonathanpalma** [comment]
@all-contributors please add @DavitVosk for ideas
