### ISSUE TITLE
Use this project to license plate recognition

### ISSUE THREAD

**Issue by costabatista** [jonathanpalma/react-native-tesseract-ocr#21]
Hi!

I need to develop a module in React Native that does license plate recognition. I'm from Brazil. Can i use this project to do this? My input is a photo from an android device.

sorry my bad English,
Thanks :)

**Comment by jonathanpalma** [comment]
Hey @costabatista Don't worry I'm not an English speaker either but I hope I could help you. 

As far as I know there is already an implementation of [OpenALPR for react-native](https://github.com/cardash/react-native-openalpr) which is an open source Automatic License Plate Recognition library written in C++ with bindings in C#, Java, Node.js, Go, and Python.

**Comment by jonathanpalma** [comment]
I'm sorry I just realized that it only works on iOS.

But maybe you could ask for help to the repo's contributors or somebody in the react community group on Facebook. 

I think that lib could be more useful than this for your type of project

![screenshot_20170614-172017](https://user-images.githubusercontent.com/12414771/27158781-11dcd888-5126-11e7-91e8-71ade0049129.png)
