### ISSUE TITLE
New project sub directory is created every time that the ocr is used

### ISSUE THREAD

**Issue by jonathanpalma** [jonathanpalma/react-native-tesseract-ocr#22]
![1](https://user-images.githubusercontent.com/12414771/28401559-eef62c70-6cd7-11e7-8e74-97c3d31b88df.jpeg)

![2](https://user-images.githubusercontent.com/12414771/28401569-fc0e1bf2-6cd7-11e7-807e-a80100e611ef.jpeg)

![3](https://user-images.githubusercontent.com/12414771/28401584-18e8120a-6cd8-11e7-9771-a2f07865c589.jpeg)

**Comment by fivepapertigers** [comment]
@jonathanpalma FYI, this seems like it's still outstanding. 59575d8df0cf5a9488b17eadbab13a31cdac97e3 has not been merged.

**Comment by jonathanpalma** [comment]
@fivepapertigers It's already published under v1.0.9 on npm 😄
