### ISSUE TITLE
Any plan for iOS?

### ISSUE THREAD

**Issue by pgwzzz** [jonathanpalma/react-native-tesseract-ocr#23]
Thanks for your job.

Is there any plan for iOS?

**Comment by danleveille** [comment]
See #8

**Comment by alburdette619** [comment]
I don't think #8 in its current enough to help us understand what is going on.  I am very confused by the end of it all.  Is this working for iOS, yes, no, or somewhere in between?  According to the README, it doesn't, but you can install it...  very confusing.

**Comment by jonathanpalma** [comment]
To have a better tracking of the iOS implementation process please follow this thread #8
