### ISSUE TITLE
Error: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference

### ISSUE THREAD

**Issue by aphex3k** [jonathanpalma/react-native-tesseract-ocr#25]
Running on Android 6.0.1 I get the above error 
```
OCR Error:  Error: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
```
when invoking
```
            RNTesseractOcr.startOcr(data["path"], "eng")
            .then((result) => {
                console.log("OCR Result: ", result);
            })
            .catch((err) => {
                console.log("OCR Error: ", err);
            })
            .done();
```

my data object looks like this
```
{path: "file:///data/user/0/com.scanocr/cache/IMG_20170914_1521561881209554.jpg"}
```

**Comment by Kaminiak** [comment]
I have the same problem :(

**Comment by SpidGiarz** [comment]
Change your language string from `eng` to the corresponding language constant `LANG_ENGLISH`

Also the path should not include the file scheme so truncate it to `/data/user/0/com.scanocr/cache/IMG_20170914_1521561881209554.jpg`

**Comment by cri5ti** [comment]
I've been having the same issue..

> Change your language string from eng to the corresponding language constant LANG_ENGLISH

What SpidGiarz means here is to actually use "LANG_ENGLISH" as the lang:

     RNTesseractOcr.startOcr(data["path"].replace(/^file:\/\//, ''), "LANG_ENGLISH")

As a side note, I was initially trying to use RNTesseractOcr.LANG_ENGLISH instead, which is defined and returns "eng".

**Comment by jonathanpalma** [comment]
As @oloyax commented, you should not include the `file://` substring as part of your path. However, since v2.0.0 the library is taking care of that under the hood. Regarding the language options, you can now import them as constants to avoid any kind of issue.

```typescript
import TesseractOcr, { LANG_ENGLISH } from 'react-native-tesseract-ocr';
```
