### ISSUE TITLE
where i can drop file v3.04 Trained data files 

### ISSUE THREAD

**Issue by EroticCode** [jonathanpalma/react-native-tesseract-ocr#26]
please help
i follow ......../asset/tessdata but not working android

**Comment by karydja** [comment]
Can you provide more info about this? For example, did you notice any errors while debugging? When I experienced this issue I had

```
Data file not found at /storage/emulated/0/br.com.testproject/br.com.testproject/br.com.testproject/tessdata/por.traineddata
```

in my console (I was running the app in my device and debugging remotely), what seems to have some relation with #22

**Comment by EroticCode** [comment]
my code is fine now is working

**Comment by SwagatRanjit84** [comment]
@karydja @EroticCode 
 Is this working on your side? WHere to drop train files?
