### ISSUE TITLE
SDK Error

### ISSUE THREAD

**Issue by damianglazer** [jonathanpalma/react-native-tesseract-ocr#27]
Hi
I have problem with sdk.
Do you update sdk in project? 

`com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : -26: Package com.example new target SDK 22 doesn't support runtime permissions but the old target SDK 25 does.`

**Comment by jonathanpalma** [comment]
Hey @dazer91 

I'm sorry for taking so long to answer but I've been pretty busy with some work stuffs. Could you please let me know if you already solved this?

**Comment by dazer91** [comment]
Hi @jonathanpalma 
No, I'm waiting for you. I have tesseract-ocr in feature. If you upgrade sdk I will be grateful.
