### ISSUE TITLE
Working with Expo

### ISSUE THREAD

**Issue by MeKyleH** [jonathanpalma/react-native-tesseract-ocr#30]
Does this project or will this project work with Expo? I'm building my app in Expo and the setup guide says I need to add things in xCode and the Android Manifest file. I'm not familiar with that process since I use Expo so I'm curious if this does or will work with Expo in the future. Thanks!

**Comment by dcherniy** [comment]
This will not work on expo. You need to eject out of `create-react-native-app`
Read the tab titled **Building Projects with Native Code**:
[https://facebook.github.io/react-native/docs/getting-started.html](url)

**Comment by jonathanpalma** [comment]
Hi @MeKyleH 

I'm sorry for taking so long to answer but I've been pretty busy with some work stuffs. As @dcherniy said it's not working on expo, in this case you'll need to eject your project in order to use it.
