### ISSUE TITLE
OCR Example App

### ISSUE THREAD

**Issue by guitar9** [jonathanpalma/react-native-tesseract-ocr#31]
hi,
i tried to run the example app. I take a photo, but the spinner is always loading. It doesnt get ready. Why?

**Comment by jonathanpalma** [comment]
Hi @guitar9

I have noticed that it happens because of the size of the image you're trying to analyze. I'm not sure if there is an open issue related to handle this

**Comment by jonathanpalma** [comment]
Hi @guitar9 

I'm closing this issue but you can follow it up on #29

**Comment by SwagatRanjit84** [comment]
@guitar9  Can you give your working code of OCR?
