### ISSUE TITLE
output is not correct in android

### ISSUE THREAD

**Issue by ghost** [jonathanpalma/react-native-tesseract-ocr#35]

**Comment by jonathanpalma** [comment]
Could you please provide more information about this?

**Comment by Rananjaya** [comment]
I have same issue.

**Comment by imran1992** [comment]
Yes. I have too. :(
I want to recognize LANG_ENGLISH.
I just copy one file `eng.traineddata` to `MyRNApp\android\app\src\main\assets\tessdata`.

**Comment by chetankotkar** [comment]
same issue am facing .. I am getting output like below..

[2019-02-19 15:36:07.843 21999-22040/com.contentreader E/RNTesseractOcr: g —z é
    , g a ’
    g. a." u»
    z a ‘g
    pan
    u m
    a in “an
    an m"“‘\
    Oabwiz
    S zézwai
    ‘Q °~~
    a susitnz“
    ﬂ  §E£ia](url)

**Comment by shiprasharma12** [comment]
Hello Guys,

In Android build using react native, the OCR is not returning the expected result.

Please provide your inputs so that I can move further in this module as I'm stuck with this issue.

Thanks, 
Shipra Sharma

**Comment by nguyenvanan18031993** [comment]
hello guys,
Same issue. I get incorrect output when scan Number in captured image from camera.
Thanks.

**Comment by Rananjaya** [comment]
same issue here. Out out not correct

**Comment by lutakyn** [comment]
i have the same issue, the text in my image is "I am Three" , the output is k. Is the trained data wrong?

**Comment by arunahuja94** [comment]
same issue here. output not correct
Any solutions?

**Comment by wadewadewadewadewadewade** [comment]
I used the 4.0 training data from here: https://github.com/tesseract-ocr/tessdata ; and the result isn't great.

When I use it on an image that has a cartoon zebra in the background partially and some sans-serif green text reading 'ZEBRA' that's huge in the image, with letters spread far apart, I get:
```
E \ '.
Z EEB'BA
```
Which isn't great, but is at least better then a handwritten pencil on white paper  with the word 'salt',  which end up just a slurry of nonsense. My ultimate goal is to recognize handwriting.

Questions:

1. Would it help if I processed the image after it was chosen to make it just black and white, and smooth out the pixels? 
2. Or maybe there are OCR threshold settings I can tinker with somewhere in the android folder?

Thanks for the help!

**Comment by lloytynoja** [comment]
@wadewadewadewadewadewade

As project uses tess-two, I think you should use 3.x training data. At least on my app, results are now better (not perfect yet, but haven't explored with image sizes nor other parameters yet). The data is available here (linked in tess-two documentation): https://github.com/tesseract-ocr/tessdata/tree/3.04.00

**Comment by isfandiarto** [comment]
i have the same problem, for me it seems to work only on image with white font and black background, other than that the result is gibberish. Any advice to this problem
