### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by mokhtars** [jonathanpalma/react-native-tesseract-ocr#37]
Hi when i run the run-android command i have this error 

What went wrong:
Execution failed for task ':react-native-image-picker:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by jonathanpalma** [comment]
Hi @mokhtars 

Did you run the command inside the tesseractOcrSample's directory?

If yes, please try to update your node_modules and run `cd android && ./gradlew clean` and let me know if that works for you.

**Comment by mokhtars** [comment]
Hi @jonathanpalma 
it had fixed the probleme, thank you for your help

**Comment by jonathanpalma** [comment]
@mokhtars you're welcome!
