### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by vitor504** [jonathanpalma/react-native-tesseract-ocr#39]
Hi,

I am trying to implement this in a project I am doing and I can't run it. It always shows me this error:

![screenshot_20180322-143702](https://user-images.githubusercontent.com/34678113/37777222-ef76a59e-2dde-11e8-99d7-6aa67ab25019.png)

I did all the steps you specified to use this but I can't seem to be able to get this to work.

Hope you can help and thanks in advance.

**Comment by jonathanpalma** [comment]
@vitor504 Could you please provide some code of your implementation?

**Comment by vitor504** [comment]
I have this in my main file:

RNTesseractOcr.recognize(source, 'LANG_ENGLISH', tessOptions)
                  .then((result) => {
                      this.setState({ ocrResult: result });
                      console.log("OCR Result: ", result);
                  })
                  .catch((err) => {
                      console.log("OCR Error: ", err);
                  })
                  .done(
                      this.setState({
                          textImg: result
                      })
                  );
And when I put my mouse over the recognize method, it shows me a warning that it is an unresolved function or method.

**Comment by vitor504** [comment]
I just created a simple project and executed all the steps you specified to make this work on my project but I just dont know if I am missing a file or something like that.
