### ISSUE TITLE
Error: Data file not found at /storage/emulated/0/com.ocr/tessdata/eng.traineddata

### ISSUE THREAD

**Issue by Rananjaya** [jonathanpalma/react-native-tesseract-ocr#41]
Error: Data file not found at /storage/emulated/0/com.ocr/tessdata/eng.traineddata

**Comment by givik** [comment]
You have to add trained data files into `android/app/src/main/assets/tessdata`.

**Comment by Rananjaya** [comment]
I put traing data in  android/app/src/main/assets/tessdata but issue is same.

**Comment by SwagatRanjit84** [comment]
@Rananjaya  Can you share your code?>
