### ISSUE TITLE
TesseractOCR/TesseractOCR.h Not found

### ISSUE THREAD

**Issue by gmaggess** [jonathanpalma/react-native-tesseract-ocr#43]
This issue has been filed before [here](https://github.com/gali8/Tesseract-OCR-iOS/issues/6), but I wondering if anyone has faced this issue lately.

I'm using RN 0.55.4 and react-native-tesseract-ocr 4.0.0.

```
In file included from /Users/gmaggess/dev/oracle/amce/omce_demos/aria_ocr/node_modules/react-native-tesseract-ocr/ios/RNTesseractOcr.m:2:
/Users/gmaggess/dev/oracle/amce/omce_demos/aria_ocr/node_modules/react-native-tesseract-ocr/ios/RNTesseractOcr.h:3:9: fatal error: 'TesseractOCR/TesseractOCR.h' file not found
#import <TesseractOCR/TesseractOCR.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **


The following build commands failed:

	CompileC /Users/gmaggess/dev/oracle/amce/omce_demos/aria_ocr/ios/build/Build/Intermediates.noindex/RNTesseractOcr.build/Debug-iphonesimulator/RNTesseractOcr.build/Objects-normal/x86_64/RNTesseractOcr.o RNTesseractOcr.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by jkaluzka** [comment]
Did you install pod and install dependencies?
You need to add 
`pod 'TesseractOCRiOS', '4.0.0'` 

to your pod file and run

`pod install`

**Comment by httol** [comment]
> Did you install pod and install dependencies?
> You need to add
> `pod 'TesseractOCRiOS', '4.0.0'`
> 
> to your pod file and run
> 
> `pod install`

I have installed the pod 'TesseractOCRiOS', '4.0.0',but still have this error

**Comment by vinsonxing** [comment]
Add one more path in Header Search Paths for the project 'RNTesseractOcr.xcodeproj'. 

$(SRCROOT)/../../../ios

**Comment by shiprasharma12** [comment]
I am getting same error. when I run it on iOS device   ,it is returning 

***** TesseractOCR/TesseractOCR.h Not found  **** 
in RNTesseractOcr.h file.

#import "RCTBridgeModule.h"
**#import <TesseractOCR/TesseractOCR.h>** 

@interface RNTesseractOcr : NSObject <RCTBridgeModule, G8TesseractDelegate>
@end


Please provide any updation on the issue.

**Comment by shahrajitechnotion** [comment]
replace 
#import "RNTesseractOcr.h"
To
#import "RNTesseractOcr.h"

**Comment by matikups** [comment]
Tried @shahrajk solution, but didn't work.
Any other suggestions?

**Comment by shahrajk** [comment]
using my solution you got the same error or any other error.
@matikups
