### ISSUE TITLE
OCR Blocking the UI

### ISSUE THREAD

**Issue by liyyil** [jonathanpalma/react-native-tesseract-ocr#44]
Seems RNTesseractOcr is blocking the UI.

I tried with TesseractOcrSample you have provided, 'cancel recognition' Button not respond.
(it should be able to run in background)

**Comment by jonathanpalma** [comment]
@liyyil you are right it's blocking the main thread. In order to solve this issue, recognize method should use `AsyncTask` to run in background.

**Comment by jonathanpalma** [comment]
@liyyil this was fixed in v2.0.0
