### ISSUE TITLE
RNTesseractOcr is undefined after import

### ISSUE THREAD

**Issue by Saerdn** [jonathanpalma/react-native-tesseract-ocr#45]
Hey,

I managed to get react native tesseract ocr run for iOS. But: When I use your example I can't use RNTesseractOcr as it is still undefined after I imported it:
import RNTesseractOcr from 'react-native-tesseract-ocr';
Does anyone has a clue how to proceed here?

Probably the same issue [here](https://github.com/jonathanpalma/react-native-tesseract-ocr/issues/40) but this time it's with iOS.

**Comment by jonathanpalma** [comment]
To have a better tracking of the iOS implementation process please follow this thread #8
