### ISSUE TITLE
Math formulas 

### ISSUE THREAD

**Issue by guitar9** [jonathanpalma/react-native-tesseract-ocr#46]
is it possilble to use it with math formulas? Or should i train my own data?

**Comment by jonathanpalma** [comment]
Even though it may work sometimes, it would work better if you provide it your own trained data for your use case.

Doing some research I found these [data files](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files) that may help you. You can try them using `LANG_CUSTOM` and naming the trained data file as `custom.traineddata`
