### ISSUE TITLE
Incompatibility with image-picker@latest

### ISSUE THREAD

**Issue by SimoneMSR** [jonathanpalma/react-native-tesseract-ocr#49]
My package.json

```
...
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-image-picker": "^0.27.1",
    "react-native-tesseract-ocr": "^1.0.10"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
...
```

Using this dependency
`com.android.tools.build:gradle:2.2.3`

When I run
`react-native run-android`
I get this error
**`Could not expand ZIP 'D:\Progetti\Vari\ReceiptScannerTesseract2\node_modules\react-native-image-picker\android\build\outputs\aar\react-native-image-picker-release.aar`**

Which image-picker version shoul I use instead?

**Comment by jonathanpalma** [comment]
Hi @SimoneMSR,

I just updated the example a few days ago.

```json
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-image-picker": "^0.28.0",
    "react-native-tesseract-ocr": "^1.0.10"
  },
```

so, with that it should be fine.

FYI: [https://github.com/jonathanpalma/react-native-tesseract-ocr/blob/master/examples/RNTesseractOcrExample/package.json#L13](https://github.com/jonathanpalma/react-native-tesseract-ocr/blob/master/examples/RNTesseractOcrExample/package.json#L13)
