### ISSUE TITLE
Can not read property 'startOcr' of undefined

### ISSUE THREAD

**Issue by diemvtt** [jonathanpalma/react-native-tesseract-ocr#5]
Hi @jonathanpalma ,
I've tried using your libs, but it appears this error.
I follow your installation step by step.

I'm a newbie in react-native and ios.
Hope you will help me to resolve this. Thank you!~~

**Comment by jonathanpalma** [comment]
Hey @diemvtt you're welcome,
I appreciate your support using my lib.
Unfortunately [iOS implementation is not ready yet](https://github.com/jonathanpalma/react-native-tesseract-ocr#todos) but I'm working on it.

Be sure I will fix it ASAP. Thank you!!

**Comment by diemvtt** [comment]
Hi @jonathanpalma, i've written code to support iOS, it's working now. But it has a little bug, because it cannot read number. But it's good when reading text. I wonder that if can i help you to update your source code to support iOS. 
And i use OCR lib from this. https://github.com/gali8/Tesseract-OCR-iOS

**Comment by jonathanpalma** [comment]
Hey @diemvtt, It sounds great!! Send a PR and I gladly accept. :smile:

**Comment by diemvtt** [comment]
Hi @jonathanpalma ,
Please wait me to integrate it to your code. Because i make it on my source code. :P.

**Comment by congnguyen91** [comment]
Is anyone supporting this :)

**Comment by jonathanpalma** [comment]
@congnguyen91 Yup!! I'm working on it!! Sorry for the delay but I am working on another projects that consume most of my time and I have very little time to dedicate maintenance to this project. But be sure what this will be fixed ASAP!!

**Comment by DavitVosk** [comment]
Hi all. I have the same issue here. I try to run this module on Android and I receive the message 'Cannot read property 'startOcr' of undefined'. console.log proves that the RNTesseractOcr is undefined. Please help to solve the problem. Thanks in advance

**Comment by DavitVosk** [comment]
@jonathanpalma Also, in the installation part it is mentioned to arrange changes in MainActivity.java, but this should be MainApplication.java. Please correct this as well

**Comment by karydja** [comment]
@diemvtt @DavitVosk I was experiencing this same issue, and in my case (Android) I need to `react-native run-android` to properly build the app

**Comment by daominhsangvn** [comment]
I have forked the project, merged the `tessBaseApiExtra` branch and add ios implementation at this fork https://github.com/newoceaninfosys/react-native-tesseract-ocr
Please check the Readme. I have updated a little bit in my fork.

**Comment by jonathanpalma** [comment]
Currently I'm living in Vancouver due to work reasons, so it's kind of hard to check this out for me, but if some of you guys @diemvtt @karydja @DavitVosk @congnguyen91 could have a look on @daominhsangvn's [fork](https://github.com/newoceaninfosys/react-native-tesseract-ocr) and give some feedback we could create a pull request

**Comment by jonathanpalma** [comment]
To have a better tracking of the iOS implementation process please follow this thread #8
