### ISSUE TITLE
Cannot find protocol declaration for 'G8TesseractDelegate'

### ISSUE THREAD

**Issue by losheredos** [jonathanpalma/react-native-tesseract-ocr#58]
I installed package with required steps such as installing pods and linking but still getting this error. I have no idea how to solve it.
This error occurs in RNTesseractOcr.xcodeproj/RNTesseractOcr.h/RNTesseractOcr

#import "RCTBridgeModule.h"
#import "RNTesseractOcr.h"

@interface RNTesseractOcr : NSObject <RCTBridgeModule, G8TesseractDelegate>

@EnD

any ideas how to solve it?

**Comment by shahrajk** [comment]
Replace this code with below my code


#import "RCTBridgeModule.h"
#import "RNTesseractOcr.h"

@class G8TesseractDelegate;
@protocol G8TesseractDelegate <NSObject>

@end

@interface RNTesseractOcr : NSObject <RCTBridgeModule, G8TesseractDelegate>

@end


this helps you to run the project successfully.
@losheredos

**Comment by losheredos** [comment]
It removed that error bug now I get another error.

Showing Recent Issues
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shahrajk** [comment]
What is your Xcode version?
and please try to delete path in the Library search path.

![image](https://user-images.githubusercontent.com/45192049/57430378-20cf1000-724d-11e9-81fe-4293293705f0.png)

**Comment by shahrajk** [comment]
After that still, you get an error then try to delete Drivedata folder.
Then Clean build Folder and run the project

**Comment by losheredos** [comment]
My version 10.1, I try now but looks like wont work, this looks like connected with react-native-image-picker but.. strange

**Comment by shahrajk** [comment]
Try once above solution after that if you got the same error or any other then we can work on it.
@losheredos

**Comment by shahrajk** [comment]
and in info.plist file you can provide required permission for image picker and camera?
@losheredos

**Comment by losheredos** [comment]
Yeah I have provided these,

> What is your Xcode version?
> try to delete path in the Library search path.
> 
> select target -> build setting -> Library search path.
> 
> ![image](https://user-images.githubusercontent.com/45192049/57430378-20cf1000-724d-11e9-81fe-4293293705f0.png)
> 
> @losheredos

why should I delete paths? Actually I deleted Image picker path but i still get the same error. Also I have required permissions for image-picker. Maybe Pods cause this issue, because I linked image-picker automatically so, instead I could try manual linking.

**Comment by shahrajk** [comment]
During automatically linking and manually linking someplace generate the same file more than one that's why this error generated I think.so check

 **build phase -> link binary with libraries**

@losheredos

**Comment by shahrajk** [comment]
you can work on this cloning project or any other project?
@losheredos

**Comment by losheredos** [comment]
I need to integrate it to my project, OK now I'm trying all, and if It wont work, I will create the project again and apply this steps and let you know. Thank you :)

**Comment by shahrajk** [comment]
Welcome
and I suggest you try first in clon project bcoz there is many more issue I facing still.
it's pretty good work in android but not in ios.

Thank you 
@losheredos

**Comment by losheredos** [comment]
Thank you too! I installed again and did all steps to add this package to my project now I'm getting error in Xcode console:

```
dyld: lazy symbol binding failed: can't resolve symbol ___cxa_guard_acquire in /Users/coolapple/Library/Developer/CoreSimulator/Devices/A4158D3B-1842-4788-980B-B5C8E341476A/data/Containers/Bundle/Application/E3E6A4B8-CA47-4EDC-AE2D-E96C0F08834C/GoProject.app/GoProject because dependent dylib #1 could not be loaded
dyld: can't resolve symbol ___cxa_guard_acquire in /Users/coolapple/Library/Developer/CoreSimulator/Devices/A4158D3B-1842-4788-980B-B5C8E341476A/data/Containers/Bundle/Application/E3E6A4B8-CA47-4EDC-AE2D-E96C0F08834C/GoProject.app/GoProject because dependent dylib #1 could not be loaded
```

**Comment by shahrajk** [comment]
I only suggest you don't do anything in your project just download clone project and try to run that project if everything works fine on this cloning project. then start implementation in your project.  
@losheredos

**Comment by losheredos** [comment]
Ok yeah I see that you are right about it, I will try it. Thank you!

**Comment by nasseh101** [comment]
@losheredos add this to your pod file 
`    pod 'TesseractOCRiOS', :git => 'git://github.com/parallaxe/Tesseract-OCR-iOS.git', :branch => 'macos-support'
`
