### ISSUE TITLE
my app Crashed EveryTime I Use  RNTesseractOcr.recognize

### ISSUE THREAD

**Issue by mahdibarati** [jonathanpalma/react-native-tesseract-ocr#59]
my app Crashed EveryTime I Use  RNTesseractOcr.recognize.
this is my code:

	ImagePicker.openCamera({
			cropping: false,
			compressImageMaxWidth: 1600,
		}).then(image => {
			console.log(image);
			const imagePath = image.path;
			this.setState({ 
				url: imagePath
			});
			const tessOptions = {
				whitelist: null, 
				blacklist: '1234567890\'!"#$%&/()={}[]+*-_:;<>'
			  };
			  path = imagePath.replace('file://', '');
			  console.log('data path', path);
			  RNTesseractOcr.recognize(path, 'LANG_ENGLISH', tessOptions)
				.then((result) => {
				  this.setState({ ocrResult: result });
				  console.log("OCR Result: ", result);
				})
				.catch((err) => {
				  console.log("OCR Error: ", err);
				})
				.done();
				
		}).catch(e => {
			console.log(e);
		});

**Comment by Salimattivenkatvinay** [comment]
I'm facing the same issue. Any solution?

**Comment by jonathanpalma** [comment]
@Salimattivenkatvinay can you please share the `react-native` and `react-native-tesseract-ocr` version you are using?

**Comment by QuentinPentalog** [comment]
Hello, I have the same issue...

Here are the information : 
`"react-native": "~0.62.2",
    "react-native-tesseract-ocr": "^2.0.1",`

**Comment by aristech** [comment]
same here  :(

`"react-native": "~0.6x.x", "react-native-tesseract-ocr": "^2.0.1",`
