### ISSUE TITLE
"Data file not found at " keep getting this error.

### ISSUE THREAD

**Issue by anupkale1984** [jonathanpalma/react-native-tesseract-ocr#6]
I was trying your sample, And i keep getting this error for file not found.

PATH - /storage/emulated/0/Pictures/image-ea1f7b95-141a-4d44-bc8f-8b76552833ed.jpg
 Timeline: Activity_idle id: android.os.BinderProxy@c792cf time:191950033
25747-25918/com.ammobile D/RNTesseractOcr: Preparing tesseract enviroment
25747-25918/com.ammobile I/RNTesseractOcr: Created directory /storage/emulated/0/com.ammobile/tessdata
25747-25918/com.ammobile D/RNTesseractOcr: Start ocr images
25747-25918/com.ammobile E/RNTesseractOcr: Data file not found at /storage/emulated/0/com.ammobile/tessdata/eng.traineddata
25747-25917/com.ammobile I/ReactNativeJS: 'OCR Error: ', { [Error: Data file not found at /storage/emulated/0/com.ammobile/tessdata/eng.traineddata] framesToPop: 1, code: 'An error occurred' }

**Comment by anupkale1984** [comment]
Got fixed: By mistake added file to wrong folder.

**Comment by jonathanpalma** [comment]
Hey @anupkale1984 I appreciate your support, that was my mistake because I omitted to mention it on the [example section](https://github.com/jonathanpalma/react-native-tesseract-ocr#example) of the README

```
RNTesseractOcr: Data file not found at /storage/emulated/0/com.ammobile/tessdata/eng.traineddata
```

**Comment by mayank-daffodil** [comment]
Can you please describe where i have to add tessdata files (https://github.com/tesseract-ocr/tessdata/tree/3.04.00) ?
