### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by broros** [jonathanpalma/react-native-tesseract-ocr#66]
Need an update for Xcode 11

```

fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>




The following build commands failed:
	CompileC /Users/brody/Desktop/showme/ios/build/showme/Build/Intermediates.noindex/RNTesseractOcr.build/Debug-iphonesimulator/RNTesseractOcr.build/Objects-normal/x86_64/RNTesseractOcr.o 

/Users/brody/Desktop/showme/node_modules/react-native-tesseract-ocr/ios/RNTesseractOcr.m 

normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

**Comment by lutakyn** [comment]
This library has never worked for me on iOS, getting React/RCTDefines.h file not found

**Comment by ducnmisbk** [comment]
1. Go to Project navigator > Libraries > RNTesseractOcr.xcodeproj
2. Click on Build Settings and then the first item under "Targets"
3. Search to edit the 'Header Search Paths'
4. Add the following entry (click '+'): ${SRCROOT}/../../../ios/Pods/Headers. Make sure to set it to recursive.
5. Clean (cmd + shift + K) and re-build (cmd + B)
