### ISSUE TITLE
 null is not an object (evaluating '_reactNativeTesseractOcr.default.recognize')

### ISSUE THREAD

**Issue by minh-dai** [jonathanpalma/react-native-tesseract-ocr#69]
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-text-detector": "0.0.6"

**Comment by shahidansari20178** [comment]
I've facing same issue please anyone have solution.

**Comment by ducnmisbk** [comment]
> I've facing same issue please anyone have solution.

try my fork: https://github.com/ducnmisbk/react-native-tesseract-ocr

**Comment by VishalTennyson** [comment]
Just link and run it again
`react-native link`
`react-native run-android`

**Comment by orinu** [comment]
Run it via React Native with Expo and get:
"null is not an object (evaluating '_reactNativeTesseractOcr.default.recognize')"

**Comment by ameyarumbleon** [comment]
Hey did anyone get a solution. Nothing is working for me.

**Comment by ARSSHEIKH** [comment]
Last updated 2 years ago, I don't think now it will work

**Comment by Productivix** [comment]
hi @yestay90 , if you clone the projet and run , it will not run at all , it is a module to ADD in a RN project : it has no RN module itself. regards
