### ISSUE TITLE
Can we get tsv format output for finding boundary of text???

### ISSUE THREAD

**Issue by VishalMathimaran** [jonathanpalma/react-native-tesseract-ocr#76]
So that we can use ‘tsv’ config file by adding tsv at the end of the command to get the TSV output

**Comment by jonathanpalma** [comment]
@VishalTennyson please try using `recognizeTokens`, it will give you bounding and confidence information for each token. Make sure you add `level` property to the TessOptions object, this will let you specify the Iterator Level (symbol, word, line, paragraph, block)
