### ISSUE TITLE
TypeError: _reactNativeTesseractOcr.default.recognize is not a function

### ISSUE THREAD

**Issue by mitjnextt** [jonathanpalma/react-native-tesseract-ocr#82]
Facing following error :

`[TypeError: _reactNativeTesseractOcr.default.recognize is not a function. (In '_reactNativeTesseractOcr.default.recognize(path, _reactNativeTesseractOcr.LANG_ENGLISH, tesseractOptions)', '_reactNativeTesseractOcr.default.recognize' is undefined)]`

Here is my code : 

```
const recognizeTextFromImage = async (path) => {
    setIsLoading(true);

    try {
      const tesseractOptions = {};
      const recognizedText = await TesseractOcr.recognize(
        path,
        LANG_ENGLISH,
        tesseractOptions,
      );
      setText(recognizedText);
    } catch (err) {
      console.error(err);
      setText('');
    }

    setIsLoading(false);
    setProgress(0);
  };
```

**Comment by jonathanpalma** [comment]
@mitjnextt can you please provide `react`, `react-native`, and `react-native-tesseract-ocr` version?

**Comment by mitjnextt** [comment]
The version are like this :
```
"react": "16.13.1",
"react-native": "0.63.1",
"react-native-tesseract-ocr": "^2.0.0",
```

**Comment by jonathanpalma** [comment]
@mitjnextt are you trying to use it on Android or iOS?

**Comment by mitjnextt** [comment]
@jonathanpalma  Update on the issue:
I have cleaned builds and now working on Android, getting scanned data in String

But on  iOS, no luck even after cleaning build

**Comment by mitjnextt** [comment]
@jonathanpalma  I think code you provided is working successfully but issue is in linking, Am I missing something on iOS?

**Comment by jonathanpalma** [comment]
@mitjnextt I am glad you were able to make it work on Android. Unfortunately, this library doesn't support iOS

**Comment by mitjnextt** [comment]
@jonathanpalma  Oh okay, Thanks for the help
