### ISSUE TITLE
I'm getting this error while installing this package -> Unsupported URL Type "link:": link:../

### ISSUE THREAD

**Issue by ajaymarathe9** [jonathanpalma/react-native-tesseract-ocr#84]
**Describe the bug**
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../

**Comment by jonathanpalma** [comment]
@ajaymarathe9 are you trying to run the example project?

**Comment by ajaymarathe9** [comment]
> @ajaymarathe9 are you trying to run the example project?

Yes, I'm trying to run example project, what is wrong with it?

**Comment by jonathanpalma** [comment]
I believe the issue is because you installed the library dependencies and also the example dependencies. In order to make it work, try to delete library node_modules and only install the example ones.

**Comment by ajaymarathe9** [comment]
> I believe the issue is because you installed the library dependencies and also the example dependencies. In order to make it work, try to delete library node_modules and only install the example ones.

Oh thanks, that's work, :) :+1:

**Comment by DavidUnzue** [comment]
This error happens to me as well on a fresh project, just trying to install the package through npm as stated in the docs:
```
npm i react-native-tesseract-ocr --save
```

Any idea?

**Comment by jonathanpalma** [comment]
@DavidUnzue can you please provide more information about the issues? What is the the `react`, `react-native` and `react-native-tesseract-ocr` you are using in your project?

**Comment by AbdelkhalekESI** [comment]
@jonathanpalma  Getting the same error using yarn or npm 
![Annotation 2020-08-09 083550](https://user-images.githubusercontent.com/34510420/89727320-61eb3c80-da1b-11ea-96ad-5079a1e36553.png)

**Comment by jonathanpalma** [comment]
In case you have any question related to this issue please feel free to follow up here https://github.com/jonathanpalma/react-native-tesseract-ocr/issues/85
