### ISSUE TITLE
Error when try to install react-native-tesseract-ocr to my react native project

### ISSUE THREAD

**Issue by jackyzsn** [jonathanpalma/react-native-tesseract-ocr#85]
**Describe the bug**
Tried install to my project got error like below.
$ npm i react-native-tesseract-ocr --save
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../

**Dependencies (please complete the following information):**
 - react: 16.13.1
 - react-native: 0.63.2
 - react-native-tesseract-ocr: 

**To Reproduce**
run "npm i react-native-tesseract-ocr --save"

**Expected behavior**

**Screenshots**
<img width="621" alt="Screen Shot 2020-08-09 at 3 57 48 PM" src="https://user-images.githubusercontent.com/33550075/89740713-338c5200-da59-11ea-978a-8becf960c35f.png">

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by jackyzsn** [comment]
Extra logs:

20 verbose stack Error: Unsupported URL Type "link:": link:../
20 verbose stack     at unsupportedURLType (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:200:15)
20 verbose stack     at fromURL (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:258:13)
20 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:77:12)
20 verbose stack     at childDependencySpecifier (/usr/local/lib/node_modules/npm/lib/install/deps.js:105:14)
20 verbose stack     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:575:15)
20 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:525:5
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
20 verbose stack     at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:523:3)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
20 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:413:5
21 verbose cwd /Users/s2986706/reactSpace/MyCapture
22 verbose Darwin 19.5.0
23 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "react-native-tesseract-ocr"
24 verbose node v14.5.0
25 verbose npm  v6.14.5
26 error code EUNSUPPORTEDPROTOCOL
27 error Unsupported URL Type "link:": link:../
28 verbose exit [ 1, true ]

**Comment by jonathanpalma** [comment]
@jackyzsn please try [v2.0.1](https://www.npmjs.com/package/react-native-tesseract-ocr/v/2.0.1)

**Comment by DavidUnzue** [comment]
@jonathanpalma @jackyzsn I just tried with v2.0.1 and can confirm that it works now 🥳 

React: 16.13.1
React Native: 0.63.2
