### ISSUE TITLE
App get crash while TesseractOcr.recognize 

### ISSUE THREAD

**Issue by UmeshBaldaniya46** [jonathanpalma/react-native-tesseract-ocr#90]
**Describe the bug**
Create new sample project add tesseract-ocr & image-picker. Add eng.traineddata file in to assets folder, and try to run

Getting error like Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14659 (Thread-5), pid 14527 (.awesomeproject), 

I have done google for that, They said you are update UI from BG thread. but i did not do any thing, i have just copy code from your sample project.  

**Dependencies (please complete the following information):**
-  "react": "16.13.1",
-  "react-native": "0.63.3",
- "react-native-image-picker": "^2.3.4",
- "react-native-tesseract-ocr": "^2.0.1"

**Screenshots**
![Screenshot 2020-10-06 at 5 59 25 PM](https://user-images.githubusercontent.com/27193416/95202032-63a86500-07fe-11eb-907d-197b7902f524.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 4.2 
 - OS: 10
 - Device: Samsung 
 - OS: 9

**Additional context**
I  have try in other system as well but same result. 

CODE
`const [isLoading, setIsLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [imgSrc, setImgSrc] = useState(null);
  const [text, setText] = useState('');

  const onSelectImage = () => {
    ImagePicker.launchImageLibrary({
      storageOptions: {
        skipBackup: true,
        path: 'images',
      },
    }, async (response) => {
      console.log('Response == ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        setImgSrc({ uri: response.path });
        await recognizeTextFromImage(response.path);
      }
    });
  }

  useEventListener('onProgressChange', (p) => {
    setProgress(p.percent / 100);
  });

  const recognizeTextFromImage = async (path) => {
    setIsLoading(true);

    try {
      const tesseractOptions = {};
      const recognizedText = await TesseractOcr.recognize(
        path,
        LANG_ENGLISH,
        tesseractOptions,
      );
      setText(recognizedText);
    } catch (err) {
      console.error(err);
      setText('');
    }

    setIsLoading(false);
    setProgress(0);
  };`

`  return (
      <>
        <StatusBar barStyle="dark-content" />
        <SafeAreaView>
          <ScrollView
            contentInsetAdjustmentBehavior="automatic"
            style={styles.scrollView}>
            <Header />
            {global.HermesInternal == null ? null : (
              <View style={styles.engine}>
                <Text style={styles.footer}>Engine: Hermes</Text>
              </View>
            )}
            <View style={styles.body}>
              <View style={styles.sectionContainer}>
                <Text style={styles.sectionTitle}>Step One</Text>
                <Button
                  // disabled={isLoading}
                  title="Pick Image"
                  onPress={() => {
                    onSelectImage()
                  }}
                />
              </View>
              <Text>{text}</Text>
              <Image style={styles.image} source={imgSrc} />
            </View>
          </ScrollView>
        </SafeAreaView>
      </>
    );`

**Comment by rchowdhe** [comment]
Hello everyone, is there any update regarding above issue? I am facing same issue.
