### ISSUE TITLE
Tesseract iOS version that works on RN

### ISSUE THREAD

**Issue by ziyafenn** [jonathanpalma/react-native-tesseract-ocr#92]
I was working on a project where we needed tesseract to read images from both android and ios and as to my latest recollection, ios version wasn't working. So i hired a developer and to my own surprise, he was able to make a native iOS Tess version to work with the RN.

Here is the link to fork: https://github.com/ziyafenn/tesseract-objc-prz

As you can see, the last commit was 2 years ago and that is exactly when i last checked it and it was working.

I hope this fork still works and it can be helpful to you.

**Comment by yf-hk** [comment]
It's so cool! Thanks very much for sharing!

**Comment by cpawar96** [comment]
is Tesseract OCR for iOS finished?

**Comment by stoplion** [comment]
iOS iOS iOS
