### ISSUE TITLE
Bug FileNotFoundException after capture image 

### ISSUE THREAD

**Issue by ChethanAndroid** [jonathanpalma/react-native-tesseract-ocr#95]
**Describe the bug**

**Dependencies (please complete the following information):**
 - react: [e.g. 16.11.0]
 - react-native: [e.g. 0.62.2]
 - react-native-tesseract-ocr: [e.g. 2.0.0]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arunahuja94** [comment]
create 

> assets/tessdata

 folders in  

> your_app_folder_name\android\app\src\main\ 

and download your required language's **traineddata** file from **https://github.com/tesseract-ocr/tessdata** and paste in 

> your_app_folder_name\android\app\src\main\assets\tessdata\

**Comment by wadewadewadewadewadewade** [comment]
This thread, and this comment in particular, may help you: https://github.com/jonathanpalma/react-native-tesseract-ocr/issues/89#issuecomment-699961143
